apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: root
  namespace: bni-v1
spec:
  virtualhost:
    fqdn: bni.ldc.int
  routes:
  - conditions: 
    - prefix: /
    services:
    - name: demo
      port: 5000
      
  
  # includes:
  # - name: v3
  #   namespace: bni-v1
  #   conditions:
  #   - prefix: /hello