apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bni-v1

bases:
- ../_base


images:
- name: harbor.letsdocloud.com/bni-demo/bni-demo
  newTag: v1

# replicas:
# - name: demo
#   count: 5