apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bni-v3

bases:
- ../_base

resources:
- ns.yaml

images:
- name: harbor.letsdocloud.com/bni-demo/bni-demo
  newTag: v3

# replicas:
# - name: demo
#   count: 5